export const categories = [
  {
    id: 'smartphones',
    name: 'Smartphones',
    image: '/images/smartphone_logo.jpeg',
    products: [
      {
        id: 'smartphone-1',
        name: 'iPhone 16',
        price: '₹79,999',
        image: '/images/iphone16.jpeg',
        deal: 'Flat ₹3,000 OFF on HDFC Cards',
        emi: 'Starts from ₹6,666/month',
        cashback: 'Get ₹2,000 cashback with HDFC Bank',
        warranty: '1 Year Apple Manufacturer Warranty',
      },
      {
        id: 'smartphone-2',
        name: 'Samsung S23',
        price: '₹69,999',
        image: '/images/galaxy_S23.jpeg',
        deal: 'Exchange offer up to ₹10,000',
        emi: 'Starts from ₹5,833/month',
        cashback: '5% off on ICICI Credit Cards',
        warranty: '1 Year Samsung Warranty',
      },
      {
        id: 'smartphone-3',
        name: 'OnePlus 13R',
        price: '₹42,000',
        image: '/images/oneplus13r.jpeg',
        deal: '10% OFF on Axis Bank Cards',
        emi: 'Starts from ₹3,500/month',
        cashback: '₹500 Amazon Pay cashback',
        warranty: '1 Year Brand Warranty',
      },
      {
        id: 'smartphone-4',
        name: 'RealmePro 14plus',
        price: '₹29,999',
        image: '/images/realme14pro.jpeg',
        deal: '₹2,000 off on first purchase',
        emi: 'Starts from ₹2,499/month',
        cashback: '10% back with Paytm Wallet',
        warranty: '1 Year Realme Warranty',
      },
    ],
  },
  {
    id: 'laptops',
    name: 'Laptops',
    image: '/images/laptoplogo.png',
    products: [
      {
        id: 'laptop-1',
        name: 'Dell Inspiron',
        price: '₹49,999',
        image: '/images/dell.jpeg',
        deal: 'Extra ₹5,000 OFF on Exchange',
        emi: '₹4,166/month',
        cashback: '10% Cashback with HDFC Debit Cards',
        warranty: '1 Year Onsite Warranty',
      },
      {
        id: 'laptop-2',
        name: 'MacBook Air',
        price: '₹89,999',
        image: '/images/macbook.jpeg',
        deal: 'Student Discount Available',
        emi: '₹7,499/month',
        cashback: '₹5,000 Apple Store Cashback',
        warranty: '1 Year AppleCare',
      },
      {
        id: 'laptop-3',
        name: 'Lenovo IdeaPad Slim 3',
        price: '₹42,999',
        image: '/images/lenovo.jpeg',
        deal: 'No Cost EMI + Free Backpack',
        emi: '₹3,583/month',
        cashback: 'Up to ₹1,000 Paytm Cashback',
        warranty: '2 Years Lenovo Warranty',
      },
      {
        id: 'laptop-4',
        name: 'Samsung Galaxy Book4',
        price: '₹61,999',
        image: '/images/samsung.jpeg',
        deal: 'Free Mouse & Bag Worth ₹2,999',
        emi: '₹5,166/month',
        cashback: '₹1,500 Cashback with Samsung Finance',
        warranty: '1 Year Warranty',
      },
    ],
  },
  {
    id: 'cameras',
    name: 'Cameras',
    image: '/images/cameralogo.png',
    products: [
      {
        id: 'camera-1',
        name: 'Canon EOS 1500D',
        price: '₹32,000',
        image: '/images/canon.jpeg',
        deal: 'Free 16GB Card & Bag',
        emi: '₹2,666/month',
        cashback: '₹500 Cashback with Amazon Pay',
        warranty: '2 Years Canon Warranty',
      },
      {
        id: 'camera-2',
        name: 'Nikon D3500',
        price: '₹35,000',
        image: '/images/nikon.jpeg',
        deal: '10% Off on First Order',
        emi: '₹2,916/month',
        cashback: '5% Cashback on HDFC Credit Card',
        warranty: '1 Year Nikon Warranty',
      },
      {
        id: 'camera-3',
        name: 'Sony Alpha 6000',
        price: '₹45,000',
        image: '/images/sony.jpeg',
        deal: 'Combo Offer with Lens Kit',
        emi: '₹3,750/month',
        cashback: 'Flat ₹1,000 Cashback',
        warranty: '1 Year Sony Warranty',
      },
      {
        id: 'camera-4',
        name: 'Fujifilm X-T200',
        price: '₹50,000',
        image: '/images/fuji.jpeg',
        deal: '₹2,000 Off on ICICI Cards',
        emi: '₹4,166/month',
        cashback: '10% Cashback on Flipkart Axis Card',
        warranty: '1 Year Fujifilm Warranty',
      },
    ],
  },
  {
    id: 'headphones',
    name: 'Headphones',
    image: '/images/headphonelogo.jpeg',
    products: [
      {
        id: 'headphone-1',
        name: 'Boat Headphones',
        price: '₹1,999',
        image: '/images/boat.png',
        deal: 'Flat ₹500 OFF',
        emi: 'Not available',
        cashback: '5% Cashback on Amazon UPI',
        warranty: '6 Months Warranty',
      },
      {
        id: 'headphone-2',
        name: 'Sony WH-1000XM4',
        price: '₹29,999',
        image: '/images/sony_headphone.jpeg',
        deal: 'No Cost EMI + Free Case',
        emi: '₹2,499/month',
        cashback: '₹2,000 Cashback on HDFC Credit Cards',
        warranty: '1 Year Sony Warranty',
      },
      {
        id: 'headphone-3',
        name: 'Apple AirPods Pro',
        price: '₹24,999',
        image: '/images/apple.jpeg',
        deal: 'Free 6 Months Apple Music',
        emi: '₹2,083/month',
        cashback: '10% Cashback with Apple Pay',
        warranty: '1 Year Apple Warranty',
      },
      {
        id: 'headphone-4',
        name: 'JBL Tune 750BTNC',
        price: '₹8,999',
        image: '/images/jbl.jpeg',
        deal: '₹1,000 Off on First Order',
        emi: '₹750/month',
        cashback: '5% Cashback on Paytm Wallet',
        warranty: '1 Year JBL Warranty',
      },
    ],
  },
  {
    id: 'speakers',
    name: 'Bluetooth Speakers',
    image: '/images/bluetoothlogo.jpeg',
    products: [
      {
        id: 'speaker-1',
        name: 'JBL Flip 5',
        price: '₹5,999',
        image: '/images/jbl_speaker.jpeg',
        deal: '₹500 OFF on Combo Purchase',
        emi: '₹499/month',
        cashback: '10% Cashback on PhonePe',
        warranty: '1 Year JBL Warranty',
      },
      {
        id: 'speaker-2',
        name: 'Sony SRS-XB12',
        price: '₹3,999',
        image: '/images/sony_speaker.jpeg',
        deal: 'Free Carry Case',
        emi: '₹333/month',
        cashback: 'Flat ₹250 Cashback on Amazon Pay',
        warranty: '1 Year Sony Warranty',
      },
      {
        id: 'speaker-3',
        name: 'Ultimate Ears Wonderboom',
        price: '₹8,999',
        image: '/images/earboom.jpeg',
        deal: 'Bundle Offer Available',
        emi: '₹750/month',
        cashback: '5% Cashback on Axis Card',
        warranty: '1 Year Warranty',
      },
      {
        id: 'speaker-4',
        name: 'Bose SoundLink Mini II',
        price: '₹14,999',
        image: '/images/bose.jpeg',
        deal: 'Limited Period Offer',
        emi: '₹1,250/month',
        cashback: '₹500 Cashback on SBI Cards',
        warranty: '1 Year Bose Warranty',
      },
    ],
  },
  {
    id: 'kids',
    name: 'Electronics for Kids',
    image: '/images/robot_kids.jpeg',
    products: [
      {
        id: 'kid-1',
        name: 'Kids Learning Tablet',
        price: '₹3,499',
        image: '/images/tablet.jpeg',
        deal: 'Free Preloaded Educational Apps',
        emi: '₹291/month',
        cashback: '₹100 Cashback on Amazon Pay',
        warranty: '6 Months Warranty',
      },
      {
        id: 'kid-2',
        name: 'Toy Drone',
        price: '₹2,999',
        image: '/images/toy_drone.jpeg',
        deal: 'Flat 20% OFF',
        emi: '₹250/month',
        cashback: '5% Cashback on UPI',
        warranty: '3 Months Warranty',
      },
      {
        id: 'kid-3',
        name: 'Remote Control Car',
        price: '₹1,499',
        image: '/images/remote_car.jpeg',
        deal: 'BOGO Offer Available',
        emi: 'Not available',
        cashback: '₹50 Cashback with Paytm',
        warranty: '6 Months Warranty',
      },
      {
        id: 'kid-4',
        name: 'Kids Smartwatch',
        price: '₹2,499',
        image: '/images/kid_watch.jpeg',
        deal: 'Back to School Offer',
        emi: '₹208/month',
        cashback: 'Flat ₹100 Cashback',
        warranty: '6 Months Warranty',
      },
    ],
  },
];
